extends: airbnb-base
parser: babel-eslint
env:
  es6: true
  node: true
  mocha: true
rules:
  global-require: 0
  func-names: 0
  no-param-reassign: 0
  arrow-body-style: 0
  object-curly-newline: 0
  no-await-in-loop: 0
  semi:
    - error
    - never
  max-len: 0
  dot-notation: 0
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
